### PR TITLE
Update README.adoc

### PR DESCRIPTION
**Pull request by toplac**
Fix typo

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@toplac Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-guides/gs-actuator-service&pullRequestId=14)!

[Click here](https://cla.pivotal.io/sync/spring?repositoryId=spring-guides/gs-actuator-service&pullRequestId=14) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by gregturn** [comment]
@toplac Thanks for fixing this bug!

**Comment by gregturn** [comment]
Obvious

**Comment by gregturn** [comment]
@toplac Thanks for the fix! Can you sign our CLA so I can merge this on in?

**Comment by toplac** [comment]
@gregturn done. But hwat about the Part

"If you are submitting an obvious fix, then you do not need to sign the CLA."

**Comment by pivotal-issuemaster** [comment]
@toplac Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-guides/gs-actuator-service&pullRequestId=14)!

**Comment by gregturn** [comment]
obvious fix

**Pull request merged**
